services:
  cassandra:
    build:
      context: ./cassandra
      dockerfile: Dockerfile
    image: shehanhetti/cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=inference_cluster
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - inference_network

  inference_router_server:
    build:
      context: ./services/inference_routing_service
      dockerfile: Dockerfile
    image: shehanhetti/inference-router-service:latest
    container_name: inference-routing-service
    ports:
      - "50051:50051"
    command: python ./main.py
    networks:
      - inference_network

  inference_service:
    build:
      context: ./services/inference_service/inference
      dockerfile: Dockerfile
    image: shehanhetti/inference-service:latest
    container_name: inference-service
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./services/inference_service/inference/app:/app
    command: >
      sh -c "while ! cqlsh -u cassandra -p cassandra cassandra -e 'DESCRIBE KEYSPACES'; do
              echo 'Waiting for Cassandra...';
              sleep 5;
            done && 
            uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - inference_network

volumes:
  cassandra-data:

networks:
  inference_network:
    name: inference_network