# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_node2_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_node2_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16llm_node2_server.proto\x12\x0ellmNode2Server\"Z\n\x0fLLMNode2Request\x12\x15\n\rhidden_states\x18\x01 \x01(\t\x12\x1c\n\x14num_return_sequences\x18\x02 \x01(\t\x12\x12\n\nmax_length\x18\x03 \x01(\t\"*\n\x10LLMNode2Response\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2h\n\rprocess_part2\x12W\n\x10GetGeneratedText\x12\x1f.llmNode2Server.LLMNode2Request\x1a .llmNode2Server.LLMNode2Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_node2_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMNODE2REQUEST']._serialized_start=42
  _globals['_LLMNODE2REQUEST']._serialized_end=132
  _globals['_LLMNODE2RESPONSE']._serialized_start=134
  _globals['_LLMNODE2RESPONSE']._serialized_end=176
  _globals['_PROCESS_PART2']._serialized_start=178
  _globals['_PROCESS_PART2']._serialized_end=282
# @@protoc_insertion_point(module_scope)
