# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inferencerouter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inferencerouter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inferencerouter.proto\x12\x06router\"%\n\rRouterRequest\x12\x14\n\x0c\x63urrent_node\x18\x01 \x01(\t\"#\n\x0eRouterResponse\x12\x11\n\tnext_node\x18\x01 \x01(\t2E\n\x06Router\x12;\n\x08GetRoute\x12\x15.router.RouterRequest\x1a\x16.router.RouterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inferencerouter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=33
  _globals['_ROUTERREQUEST']._serialized_end=70
  _globals['_ROUTERRESPONSE']._serialized_start=72
  _globals['_ROUTERRESPONSE']._serialized_end=107
  _globals['_ROUTER']._serialized_start=109
  _globals['_ROUTER']._serialized_end=178
# @@protoc_insertion_point(module_scope)
