---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-routing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-routing-service
  template:
    metadata:
      labels:
        app: inference-routing-service
    spec:
      containers:
        - name: inference-routing-service
          image: shehanhetti/inference-router-service:latest
          imagePullPolicy: Always # Change this if container is in a registry
          ports:
            - name: grpc  # Name for the gRPC port
              containerPort: 50051  # gRPC server port
            - name: metrics  # Name for the metrics port
              containerPort: 8001  # Prometheus metrics port
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-routing-service
spec:
  selector:
    app: inference-routing-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP