---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-service
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
        - name: inference-service
          image: shehanhetti/inference-service:latest
          imagePullPolicy: IfNotPresent # Change this if container is in a registry
          ports:
            - containerPort: 8000
          env:
            - name: CASSANDRA_HOST
              value: cassandra
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
